# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
'use_frameworks!'

target 'Test_App' do

pod 'iOSDropDown'
pod 'Cosmos', '~> 23.0'
pod 'SwiftyStepper'
end
